// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsJHWmO8TXUoqJbaAh4BjzLvdcNbmcN1c',
    appId: '1:654879732620:web:80ecdfca82e5cf5e2b9ca9',
    messagingSenderId: '654879732620',
    projectId: 'codingcorner-1f079',
    authDomain: 'codingcorner-1f079.firebaseapp.com',
    storageBucket: 'codingcorner-1f079.firebasestorage.app',
    measurementId: 'G-3N251LVRHB',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCt_1R_Vbum2ldiL_I3nz8ID4BuYnWeSE',
    appId: '1:654879732620:ios:4b35bcb863ee799d2b9ca9',
    messagingSenderId: '654879732620',
    projectId: 'codingcorner-1f079',
    storageBucket: 'codingcorner-1f079.firebasestorage.app',
    iosBundleId: 'com.example.codingCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCt_1R_Vbum2ldiL_I3nz8ID4BuYnWeSE',
    appId: '1:654879732620:ios:4b35bcb863ee799d2b9ca9',
    messagingSenderId: '654879732620',
    projectId: 'codingcorner-1f079',
    storageBucket: 'codingcorner-1f079.firebasestorage.app',
    iosBundleId: 'com.example.codingCorner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsJHWmO8TXUoqJbaAh4BjzLvdcNbmcN1c',
    appId: '1:654879732620:web:ba4418a1064df2e82b9ca9',
    messagingSenderId: '654879732620',
    projectId: 'codingcorner-1f079',
    authDomain: 'codingcorner-1f079.firebaseapp.com',
    storageBucket: 'codingcorner-1f079.firebasestorage.app',
    measurementId: 'G-SD43L36NWS',
  );
}
